skeeto/elfeed

elfeed-show.el
While  sexp ''(kill-new link)" is present in function elfeed-search-yank, it is missing from elfeed-show-yank. Pressing y in entry window has not been adding the article URL to the clipboard in OS X. Adding this sexp fixes it.
=> elfeed-show.el: fix yank to clipboard in OSX

elfeed-search.el
This commit adds docstrings to three of the more fundamental functions
of the elfeed interface. The docstrings themselves are fairly
self-explanatory, but including helps to round out the package's
presence in Emacs' built-in documentation system.
=> search-{tag,untag}-all, search-update: docstrings

elfeed-search.el
Add a `kbd-help` property with the full title of the entry in the search view so
it can be displayed with `C-h .`.
=> elfeed-search.el (elfeed-search-print): Display title with `C-h .`

web/elfeed-web.el
Not sure if it's right fix, but now `elfeed-search-filter` accepts `count`. And looks like passing `elfeed-web-limit` is the right thing. 
This PR is proposed in order to fix problem with `elfeed-web` when it gets internal server error on search.
=> fix elfeed/search endpoint

elfeed.el
To make the logs more useful, add a few faces to it: date and log level are now propertized, so it is easier to distinguish log levels, and easier to spot where the log message starts.
=> elfeed-log: Propertize parts of the log message

elfeed-show.el
C-u b now uses generic in view as in search
=> Synchronize prefix argument for browse-url in search and show

elfeed-curl.el, elfeed.el
Patch adds missing defcustom types/groups for curl-related settings.
=> Add missing defcustom keys

elfeed-show.el
Some of the feeds that I subscribe to have a few contributing authors, and if this is available in the metadata for an entry, I think it's nice to have an option to show it.
I added this as a customizable option which is off by default. The "author" is taken from the metadata of `elfeed-show-entry`, and is only shown in the `elfeed-entry` buffer if it's present and the option is enabled (i.e. `elfeed-show-entry-author` is non-nil).
=> Add elfeed-show-entry-author.

elfeed-link.el
This is based on #34 but also stores all the related entry metadata, so they can be used in capture templates.
Also adds support for org mode 9+ which uses different link syntax/functions.
For use in templates, you can use all the metadata under `:elfeed-entry-` namespace, for example
```elisp
("l" "Read later" entry (file "~/org/refile.org")
"* %?%:description :readlater:
- %:link
%(when (< 0 (length \"%:elfeed-entry-link\")) (concat \"- web link: \" \"%:elfeed-entry-link\"))")
```
=> Add support for org links.

elfeed-search.el, elfeed-show.el
Since Elfeed rolls its own major modes instead of using `define-derived-mode`, it runs its own hooks manually using `run-hooks`.
However, `define-derived-mode` uses `run-mode-hook`, not `run-hooks`. As a consequence,  Elfeed's major modes do not currently run the universal `change-major-mode-after-body-hook` and `after-change-major-mode-hook`, which some packages rely on to detect major mode changes.
This PR replaces `run-hooks` with `run-mode-hooks` in `elfeed-search-mode` and `elfeed-show-mode` to resolve this issue.
I don't know what the original rationale was for using the regular `run-hooks`, so please feel free to reject this if there is a good reason!
=> Use run-mode-hooks in show- and search-mode.

elfeed-db.el, elfeed-search.el, elfeed.el
With the new added elfeed-update-function, elfeed-tag-hooks and
elfeed-untag-hooks, it will be more easily to support extra elfeed
backends.
The ownCloud News in `elfeed-backends` works well now, you could have a try with the 10 minutes tutorial in README:
https://github.com/fasheng/elfeed-backends
BTW: what do you think about the design in this patch, any advice?
=> Make extra backends works more easily

elfeed-show.el
Hello,
it is a minor update, but I realise that emms-play-url is actualling cleaning the playlist before adding the track. Therefore I added a small hack based on emms-browser-add-tracks-and-play which consists of
appending the stream to the playlist and play it. The second commit is also adding support to just add the enclosure at the end of the playlist.
=> Emms update

elfeed-link.el
Because of the internal changes in Emacs cl implementation the "introspection" I've used to get the list of properties of the structure stopped working in Emacs 25.2+
I think it's not worth the effort to support multiple Emacs versions/cl implementations so I've just replaced the reflection with a static list.  Given how stable the elfeed data structures are there should never be a need to change the code very much.
=> Use hard-coded list instead of dynamic discovery

elfeed.el
The flag is always set when using the command interactively.
Also use ‘equal’ as the test predicate for ‘cl-pushnew’ as the list
contains strings.
=> Allow passing a flag to ‘elfeed-add-feed’ to save the new feed list.

elfeed-link.el
Due to the fix for #208, elfeed gets loaded after org-mode. I use org-mode extensively but do not use elfeed-link at all, and I don't want elfeed to be loaded in those situations. This provides an alternative solution to #208 that does not force elfeed to be loaded after org-mode. Instead, it binds autoloads to the functions that org-mode would invoke. I tested an elfeed link to confirm that elfeed would actually get loaded if you attempted to open the link.
=> Autoload all of elfeed-link

elfeed-show.el
Rationale: `b` opens the link and `y` saves it to the kill-ring, which
are the two primary things you’d want to do.  But since it’s a link,
you have to tab past it to get to the (different) link(s) in the
message body, which is annoying.
This PR causes TAB to skip past the message headers automatically,
preventing this annoyance.
=> In `elfeed-show-mode`, make TAB skip the link in the headers.

elfeed-show.el
This corrects a bug I introduced in #313.
`EMMS-PLAYLIST-SELECT-LAST` selects a track, but because it’s inside a
`SAVE-EXCURSION` form, point doesn’t move.  This means that when
`EMMS-PLAYLIST-MODE-PLAY-CURRENT-TRACK` runs, it may play a different
track than the one that was just added -- whichever one is under
point, or the next track from that position.  This seems to work with
simple playlists, but fails when you have other things playing or
several entries.
Instead, use `EMMS-PLAYLIST-LAST`, which moves point, and wrap both
forms in `SAVE-EXCURSION` to avoid changing the buffer out from under
the user.
=> Fix playing when there are multiple tracks on the playlist

README.md, elfeed-lib.el, elfeed-search.el, tests/elfeed-lib-tests.el, tests/elfeed-search-tests.el
This allows to specify date/time ranges as well as absolute dates/times in filters as discussed in #305.
Examples for ranges are `"@2019-06-24--2019-06-24"` or `"@5-days-ago--1-day-ago"` with the meaning that entries need to be newer than the first value and older than the second.
=> Absolute dates + filter with time ranges

elfeed-search.el
Make filter clearing update the search view.
Make ">" go to the last RSS article rather than the end of the buffer by backing up two lines.
=> Refine behavior of "c", "<", and ">" keybindings.

web/elfeed-web.el
Since Emacs 26.1 'ffloor' only accepts floating-point arguments.
I got an empty page on when loading `/elfeed`, because of:
```
(request
(date "Fr,  6 Sep 2019 20:00:07 GMT")
(address "127.0.0.1")
(get "/elfeed/update")
(headers
("GET" "/elfeed/update?time=0" "HTTP/1.1")
("Host" "localhost:8080")
("Connection" "keep-alive")
("Accept" "application/json, text/plain, */*")
("X-Requested-With" "XMLHttpRequest")
("User-Agent" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36")
("Sec-Fetch-Mode" "cors")
("Sec-Fetch-Site" "same-origin")
("Referer" "http://localhost:8080/elfeed/")
("Accept-Encoding" "gzip, deflate, br")
("Accept-Language" "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7")
("Content" "")))
(error 500
(wrong-type-argument floatp 0))
```
=> Convert the update time explicitly to float

elfeed-search.el
When non-nil, keep point at entry after performing a command.
When nil, move to next entry.
=> Add user option elfeed-search-remain-on-entry

elfeed-search.el
According to the docstring of bookmark-jump:
You may have a problem using this function if the value of
variable ‘bookmark-alist’ is nil. If that happens, you need to
load in some bookmarks. See help on function ‘bookmark-load’ for
more about this.
So e.g. binding a key to jump to an elfeed bookmark will cause an
error without first loading bookmarks.
=> Ensure bookmarks are loaded for elfeed-search

README.md, elfeed-search.el
This allows to specify several feeds to be excluded from the elfeed-search buffer, as discussed in #347.
I have modified 4 functions :
- elfeed-search-parse-filter
- elfeed-search-unparse-filter
- elfeed-search-filter
- elfeed-search-compile-filter
I have simply added a special character ('~') in the first two functions, and added a condition in the last two : similarly to =, if the entry's feed name or id matches **any** the ~-prepended strings, it is excluded.
The modified repo builds correctly (make gives no errors) and passes all the tests (make check is satisfied), although I haven't included any new ones. I have tested the package manually on the new features, though, and it works : the amount of entries with ~%s plus the amount of entries with =%s is always equal to the amount …
=> Implemented "exclude feed" functionality.

elfeed-show.el
In many situation, I need to copy out the link URL to other places.
=> Add a command keybinding to kill link URL into kill-ring

elfeed-search.el, elfeed-show.el
Simplify series of `plist-get` assignments with `cl-destructuring-bind`.
=> Refactor: leverage cl-destructuring-bind

elfeed-show.el
These functions expected `#'elfeed-search-show-entry` would move forward one
line. However, when `elfeed-search-remain-on-entry` is set to `t`, it won't, so we
need to do it manually.
=> Fix up elfeed-show-next/prev

elfeed-curl.el
This is very minor, but I feel users shouldn't be queried about ephemeral processes like the asynchronous instances of `curl` spawned by Elfeed.
If the processes are old, they will probably time out and there is no harm in killing them. If they are young, then the user's plans presumably changed right after calling `elfeed-update`, and a query would only serve as an obstruction.
(You may also wish to call `set-process-sentinel` in the line after the one I added, for consistency.)
=> No longer query users about running curl processes

elfeed-search.el
I think you should also swap the order of these two functions.
=> Fix comment and last-entry behaviour

elfeed-curl.el, elfeed-lib.el, elfeed-search.el, tests/elfeed-lib-tests.el, tests/elfeed-tests.el
Emacs version 29.0.50 has deprecated the use of forms such as `(setf (point) n)`. The warning emitted is: -
```
Warning (bytecomp): ‘point’ is an obsolete generalized variable; use ‘goto-char’ instead.
```
=> Change `(setf (point) ...)` and similar forms to `(goto-char ...)`
